const path = require("path");
const webpack = require('webpack')

const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ServiceWorkerWepbackPlugin = require('serviceworker-webpack-plugin');

module.exports = {
    context: path.resolve(__dirname, "src"),
    entry: "./scripts/site.js",
    target: "web",
    optimization: {
        minimize: false
    },
    resolve: {
        modules: [
            path.resolve(__dirname, 'src'),
            path.resolve(__dirname, "node_modules")
        ],
        alias: {
            actionsheet: "components/actionsheet/actionsheet",
            alert: "components/alert",
            alphaNumericShortcuts: "components/alphanumericshortcuts/alphanumericshortcuts",
            alphaPicker: "components/alphapicker/alphapicker",
            apiclient: "libraries/apiclient/apiclient",
            apiClientResolver: "scripts/apiClientResolver",
            appFooter: "components/appfooter/appfooter",
            "appFooter-shared": "scripts/appFooter-shared",
            appRouter: "scripts/appRouter",
            appSettings: "scripts/appSettings",
            appStorage: "scripts/appStorage",
            apphost: "components/apphost",
            autoFocuser: "scripts/autoFocuser",
            autoPlayDetect: "components/playback/autoplaydetect",
            backdrop: "scripts/backdrop",
            brightnessOsd: "scripts/brightnessOsd",
            browser: "scripts/browser",
            browserdeviceprofile: "scripts/browserdeviceprofile",
            cardBuilder: "scripts/cardBuilder",
            castSenderApiLoader: "scripts/castSenderApiLoader",
            cardStyle: "scripts/cardStyle",
            chaptercardbuilder: "scripts/chaptercardbuilder",
            chromecastHelper: "scripts/chromecastHelper",
            clearButtonStyle: "scripts/clearButtonStyle",
            collectionEditor: "scripts/collectionEditor",
            confirm: "scripts/confirm",
            connectionManager: "scripts/connectionManager",
            connectionManagerFactory: "scripts/connectionManagerFactory",
            credentialprovider: "scripts/credentialprovider",
            dashboardcss: "scripts/dashboardcss",
            datetime: "scripts/datetime",
            deleteHelper: "scripts/deleteHelper",
            dialog: "components/dialog/dialog",
            dialogHelper: "components/dialogHelper/dialogHelper",
            directorybrowser: "scripts/directorybrowser",
            displaySettings: "scripts/displaySettings",
            "document-register-element": "document-register-element",
            dom: "scripts/dom",
            elementsPath: "",
            "emby-button": "elements/emby-button/emby-button",
            "emby-checkbox": "scripts/emby-checkbox",
            "emby-collapse": "scripts/emby-collapse",
            "emby-input": "scripts/emby-input",
            "emby-itemrefreshindicator": "scripts/emby-itemrefreshindicator",
            "emby-itemscontainer": "scripts/emby-itemscontainer",
            "emby-playstatebutton": "scripts/emby-playstatebutton",
            "emby-progressring": "scripts/emby-progressring",
            "emby-radio": "scripts/emby-radio",
            "emby-ratingbutton": "scripts/emby-ratingbutton",
            "emby-scrollbuttons": "scripts/emby-scrollbuttons",
            "emby-scroller": "scripts/emby-scroller",
            "emby-select": "scripts/emby-select",
            "emby-slider": "scripts/emby-slider",
            "emby-tabs": "scripts/emby-tabs",
            "emby-textarea": "scripts/emby-textarea",
            "emby-toggle": "scripts/emby-toggle",
            "events": "scripts/events",
            experimentalwarnings: "components/playback/experimentalwarnings",
            fetch: "scripts/fetch",
            fetchHelper: "scripts/fetchHelper",
            fileDownloader: "scripts/fileDownloader",
            filerepository: "scripts/filerepository",
            filterMenu: "scripts/filterMenu",
            filesystem: "scripts/filesystem",
            flexStyles: "scripts/flexStyles",
            flvjs: "flvjs",
            fnchecked: "scripts/fnchecked",
            focusManager: "components/focusManager",
            focusPreventScroll: "scripts/focusPreventScroll",
            formDialogStyle: "scripts/formDialogStyle",
            "fullscreen-doubleclick": "scripts/fullscreen-doubleclick",
            fullscreenManager: "scripts/fullscreenManager",
            globalize: "scripts/globalize",
            "guide-settings-dialog": "scripts/guide-settings-dialog",
            headroom: "scripts/headroom",
            hlsjs: "hlsjs",
            homescreenSettings: "scripts/homescreenSettings",
            homeSections: "scripts/homeSections",
            howler: "howler",
            htmlMediaHelper: "scripts/htmlMediaHelper",
            humanedate: "components/humanedate",
            idb: "scripts/idb",
            indicators: "scripts/indicators",
            imageDownloader: "scripts/imageDownloader",
            imageEditor: "scripts/imageEditor",
            imageFetcher: "scripts/imageFetcher",
            imageLoader: "scripts/imageLoader",
            imageoptionseditor: "components/imageoptionseditor/imageoptionseditor",
            imageUploader: "scripts/imageUploader",
            inputManager: "scripts/inputManager",
            itemContextMenu: "scripts/itemContextMenu",
            itemHelper: "components/itemhelper",
            itemIdentifier: "scripts/itemIdentifier",
            itemMediaInfo: "scripts/itemMediaInfo",
            itemrepository: "scripts/itemrepository",
            itemsTab: "scripts/itemsTab",
            itemShortcuts: "components/shortcuts",
            jstree: "jstree",
            keyboardnavigation: "scripts/keyboardnavigation",
            layoutManager: "scripts/layoutManager",
            "lazyLoader": "components/lazyloader/lazyloader-intersectionobserver",
            legacyDashboard: "scripts/legacyDashboard",
            legacySelectMenu: "scripts/legacySelectMenu",
            libjass: "libjass",
            libraryBrowser: "scripts/librarybrowser",
            libraryMenu: "scripts/librarymenu",
            listView: "scripts/listView",
            listViewStyle: "scripts/listViewStyle",
            loading: "scripts/loading",
            loadingDialog: "scripts/loadingDialog",
            localassetmanager: "scripts/localassetmanager",
            localsync: "scripts/localsync",
            mainTabsManager: "scripts/mainTabsManager",
            "material-icons": "scripts/material-icons",
            "material-design-icons-iconfont": "material-design-icons-iconfont",
            mediaInfo: "scripts/mediaInfo",
            medialibrarycreator: "components/medialibrarycreator/medialibrarycreator",
            medialibraryeditor: "components/medialibraryeditor/medialibraryeditor",
            mediaSession: "scripts/mediaSession",
            mediasync: "scripts/mediasync",
            metadataEditor: "scripts/metadataEditor",
            "multi-download": "scripts/multi-download",
            multiSelect: "scripts/multiSelect",
            multiserversync: "scripts/multiserversync",
            "native-promise-only": "native-promise-only",
            navdrawer: "scripts/navdrawer",
            nowPlayingHelper: "components/playback/nowplayinghelper",
            objectassign: "scripts/objectassign",
            packageManager: "components/packagemanager",
            page: "libraries/pagejs/page",
            "paper-icon-button-light": "scripts/paper-icon-button-light",
            peoplecardbuilder: "scripts/peoplecardbuilder",
            personEditor: "scripts/personEditor",
            playaccessvalidation: "components/playback/playaccessvalidation",
            playbackManager: "scripts/playbackManager",
            playbackSettings: "scripts/playbackSettings",
            playerSelectionMenu: "scripts/playerSelectionMenu",
            playerSettingsMenu: "scripts/playerSettingsMenu",
            playerStats: "scripts/playerStats",
            playMenu: "scripts/playMenu",
            playMethodHelper: "scripts/playMethodHelper",
            playQueueManager: "components/playback/playqueuemanager",
            playlistEditor: "scripts/playlistEditor",
            pluginManager: "components/pluginManager",
            programStyles: "scripts/programStyles",
            prompt: "scripts/prompt",
            qualityoptions: "components/qualityoptions",
            queryString: "scripts/queryString",
            recordingButton: "scripts/recordingButton",
            recordingCreator: "scripts/recordingCreator",
            recordingEditor: "scripts/recordingEditor",
            recordingFields: "scripts/recordingFields",
            recordingHelper: "scripts/recordingHelper",
            refreshDialog: "scripts/refreshDialog",
            ResizeObserver: "scripts/ResizeObserver",
            "resize-observer-polyfill": "resize-observer-polyfill",
            sanitizefilename: "scripts/sanitizefilename",
            screensaverManager: "components/screensavermanager",
            scroller: "scripts/scroller",
            scrollHelper: "scripts/scrollHelper",
            scrollManager: "scripts/scrollManager",
            scrollStyles: "scripts/scrollStyles",
            searchFields: "scripts/searchFields",
            searchResults: "scripts/searchResults",
            seriesRecordingEditor: "scripts/seriesRecordingEditor",
            serverNotifications: "scripts/serverNotifications",
            serverRestartDialog: "scripts/serverRestartDialog",
            serversync: "scripts/serversync",
            shaka: "shaka",
            shell: "scripts/shell",
            skinManager: "components/skinManager",
            slideshow: "scripts/slideshow",
            sortable: "sortable",
            subtitleAppearanceHelper: "scripts/subtitleAppearanceHelper",
            subtitleEditor: "scripts/subtitleEditor",
            subtitleSettings: "scripts/subtitleSettings",
            subtitleSync: "scripts/subtitleSync",
            swiper: "swiper",
            systemFontsCss: "scripts/systemFontsCss",
            systemFontsSizedCss: "scripts/systemFontsSizedCss",
            tabbedView: "scripts/tabbedView",
            themeloader: "scripts/themeloader",
            toast: "scripts/toast",
            touchHelper: "scripts/touchHelper",
            transfermanager: "scripts/transfermanager",
            tunerPicker: "scripts/tunerPicker",
            tvguide: "scripts/tvguide",
            tvproviders: "components/tvproviders",
            upNextDialog: "scripts/upNextDialog",
            useractionrepository: "scripts/useractionrepository",
            userdataButtons: "scripts/userdataButtons",
            userSettingsBuilder: "scripts/userSettingsBuilder",
            sortMenu: "scripts/sortMenu",
            userSettings: "scripts/userSettings",
            viewContainer: "components/viewContainer",
            viewManager: "scripts/viewManager",
            viewSettings: "scripts/viewSettings",
            visibleinviewport: "components/visibleinviewport",
            webcomponents: "webcomponents"
        }
    },
    resolveLoader: {
        alias: {
            text: "file-loader",
            css: "style-loader"
        }
    },
    plugins: [
        new CleanWebpackPlugin(),
        new CopyWebpackPlugin([
            { from: '../src/*.html', to: '.' },
            { from: '../src/assets/img/*', to: '.' },
            { from: '../src/strings/*', to: '.' },
            { from: '../src/favicon.ico', to: '.' },
            { from: '../src/touchicon.png', to: '.' },
            { from: '../src/serviceworker.js', to: '.' },
            { from: '../src/themes', to: './themes' }
        ]),
        new webpack.ProvidePlugin({
            $: require.resolve('jquery'),
            jQuery: require.resolve('jquery')
        }),
        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: 'index.html'
        }),
        new ServiceWorkerWepbackPlugin({
            entry: path.join(__dirname, 'src/serviceworker.js')
        })
    ]
};
