import { LibraryApiGetItemsRequest } from '@jellyfin/sdk/lib/generated-client/api/library-api';

const split = (value?: string | string[]): string[] | undefined => {
    if (Array.isArray(value)) {
        return value;
    }
    return !!value && typeof value === 'string' ? value.split(',') : undefined;
};

export const convertFilterValuesToItemsQuery = (input: Record<string, never>, userId: string): LibraryApiGetItemsRequest => {
    return {
        userId: userId ?? input.UserId,
        maxOfficialRating: input.MaxOfficialRating,
        hasThemeSong: input.HasThemeSong,
        hasThemeVideo: input.HasThemeVideo,
        hasSubtitles: input.HasSubtitles,
        hasSpecialFeature: input.HasSpecialFeature,
        hasTrailer: input.HasTrailer,
        adjacentTo: input.AdjacentTo,
        indexNumber: input.IndexNumber,
        parentIndexNumber: input.ParentIndexNumber,
        hasParentalRating: input.HasParentalRating,
        isHd: input.IsHd,
        is4K: input.Is4K,
        locationTypes: split(input.LocationTypes) as LibraryApiGetItemsRequest['locationTypes'],
        excludeLocationTypes: split(input.ExcludeLocationTypes) as LibraryApiGetItemsRequest['excludeLocationTypes'],
        isMissing: input.IsMissing,
        isUnaired: input.IsUnaired,
        minCommunityRating: input.MinCommunityRating,
        minCriticRating: input.MinCriticRating,
        minPremiereDate: input.MinPremiereDate,
        minDateLastSaved: input.MinDateLastSaved,
        minDateLastSavedForUser: input.MinDateLastSavedForUser,
        maxPremiereDate: input.MaxPremiereDate,
        hasOverview: input.HasOverview,
        hasImdbId: input.HasImdbId,
        hasTmdbId: input.HasTmdbId,
        hasTvdbId: input.HasTvdbId,
        isMovie: input.IsMovie,
        isSeries: input.IsSeries,
        isNews: input.IsNews,
        isKids: input.IsKids,
        isSports: input.IsSports,
        excludeItemIds: split(input.ExcludeItemIds) as LibraryApiGetItemsRequest['excludeItemIds'],
        startIndex: input.StartIndex,
        limit: input.Limit,
        recursive: input.Recursive,
        searchTerm: input.SearchTerm,
        sortOrder: split(input.SortOrder) as LibraryApiGetItemsRequest['sortOrder'],
        parentId: input.ParentId,
        fields: split(input.Fields) as LibraryApiGetItemsRequest['fields'],
        excludeItemTypes: split(input.ExcludeItemTypes) as LibraryApiGetItemsRequest['excludeItemTypes'],
        includeItemTypes: split(input.IncludeItemTypes) as LibraryApiGetItemsRequest['includeItemTypes'],
        filters: split(input.Filters) as LibraryApiGetItemsRequest['filters'],
        mediaTypes: split(input.MediaTypes) as LibraryApiGetItemsRequest['mediaTypes'],
        imageTypes: split(input.ImageTypes) as LibraryApiGetItemsRequest['imageTypes'],
        sortBy: split(input.SortBy) as LibraryApiGetItemsRequest['sortBy'],
        isPlayed: input.IsPlayed,
        genres: split(input.Genres) as LibraryApiGetItemsRequest['genres'],
        officialRatings: split(input.OfficialRatings) as LibraryApiGetItemsRequest['officialRatings'],
        tags:split(input.Tags) as LibraryApiGetItemsRequest['tags'],
        years: split(input.Years)?.map(Number) as LibraryApiGetItemsRequest['years'],
        enableUserData: input.EnableUserData,
        imageTypeLimit: input.ImageTypeLimit,
        enableImageTypes: split(input.EnableImageTypes) as LibraryApiGetItemsRequest['enableImageTypes'],
        person: input.Person,
        personIds: split(input.PersonIds) as LibraryApiGetItemsRequest['personIds'],
        personTypes: split(input.PersonTypes) as LibraryApiGetItemsRequest['personTypes'],
        studios: split(input.Studios) as LibraryApiGetItemsRequest['studios'],
        artists: split(input.Artists) as LibraryApiGetItemsRequest['artists'],
        excludeArtistIds: split(input.ExcludeArtistIds) as LibraryApiGetItemsRequest['excludeArtistIds'],
        artistIds: split(input.ArtistIds) as LibraryApiGetItemsRequest['artistIds'],
        albumArtistIds: split(input.AlbumArtistIds) as LibraryApiGetItemsRequest['albumArtistIds'],
        contributingArtistIds: split(input.ContributingArtistIds) as LibraryApiGetItemsRequest['contributingArtistIds'],
        albums: split(input.Albums) as LibraryApiGetItemsRequest['albums'],
        albumIds: split(input.AlbumIds) as LibraryApiGetItemsRequest['albumIds'],
        ids: split(input.Ids) as LibraryApiGetItemsRequest['ids'],
        videoTypes: split(input.VideoTypes) as LibraryApiGetItemsRequest['videoTypes'],
        minOfficialRating: input.MinOfficialRating,
        isLocked: input.IsLocked,
        isPlaceHolder: input.IsPlaceHolder,
        hasOfficialRating: input.HasOfficialRating,
        collapseBoxSetItems: input.CollapseBoxSetItems,
        minWidth: input.MinWidth,
        minHeight: input.MinHeight,
        maxWidth: input.MaxWidth,
        maxHeight: input.MaxHeight,
        is3D: input.Is3D,
        seriesStatus: split(input.SeriesStatus) as LibraryApiGetItemsRequest['seriesStatus'],
        nameStartsWithOrGreater: input.NameStartsWithOrGreater,
        nameStartsWith: input.NameStartsWith,
        nameLessThan: input.NameLessThan,
        studioIds: split(input.StudioIds) as LibraryApiGetItemsRequest['studioIds'],
        genreIds: split(input.GenreIds) as LibraryApiGetItemsRequest['genreIds'],
        audioLanguages: split(input.AudioLanguages) as LibraryApiGetItemsRequest['audioLanguages'],
        subtitleLanguages: split(input.SubtitleLanguages) as LibraryApiGetItemsRequest['subtitleLanguages'],
        enableTotalRecordCount: input.EnableTotalRecordCount,
        enableImages: input.EnableImages
    };
};
