FROM node:alpine

ARG SOURCE_DIR=/src
ARG ARTIFACT_DIR=/jellyfin-web

RUN apk add autoconf g++ make libpng-dev gifsicle alpine-sdk automake libtool make gcc musl-dev nasm python

WORKDIR ${SOURCE_DIR}
COPY . .

RUN npm ci --no-audit && mv dist ${ARTIFACT_DIR}
