import type { BaseItemDto } from '@jellyfin/sdk/lib/generated-client';

export interface QueryI {
    SortBy?: string;
    SortOrder?: string;
    IncludeItemTypes?: string;
    Recursive?: boolean;
    Fields?: string;
    ImageTypeLimit?: number;
    EnableTotalRecordCount?: boolean;
    EnableImageTypes?: string;
    StartIndex?: number;
    ParentId?: string | null;
    IsFavorite?: boolean;
    IsMissing?: boolean;
    Limit?:number;
    NameStartsWithOrGreater?: string;
    NameLessThan?: string;
    NameStartsWith?: string | null;
    VideoTypes?: string;
    GenreIds?: string;
    Is4K?: boolean;
    IsHD?: boolean;
    Is3D?: boolean;
    HasSubtitles?: boolean;
    HasTrailer?: boolean;
    HasSpecialFeature?: boolean;
    HasThemeSong?: boolean;
    HasThemeVideo?: boolean;
    Filters?: string | null;
}

export interface FiltersI {
    IsPlayed: boolean;
    IsUnplayed: boolean;
    IsFavorite: boolean;
    IsResumable: boolean;
    Is4K: boolean;
    IsHD: boolean;
    IsSD: boolean;
    Is3D: boolean;
    VideoTypes: string;
    SeriesStatus: string;
    HasSubtitles: string;
    HasTrailer: string;
    HasSpecialFeature: string;
    HasThemeSong: string;
    HasThemeVideo: string;
    GenreIds: string;
}

export interface CardOptionsI {
    itemsContainer?: HTMLElement | null;
    parentContainer?: HTMLElement | null;
    items?: BaseItemDto[] | null;
    allowBottomPadding?: boolean;
    centerText?: boolean;
    coverImage?: boolean;
    inheritThumb?: boolean;
    overlayMoreButton?: boolean;
    overlayPlayButton?: boolean;
    overlayText?: boolean;
    preferThumb?: boolean;
    preferDisc?: boolean;
    preferLogo?: boolean;
    scalable?: boolean;
    shape?: string | null;
    lazy?: boolean;
    cardLayout?: boolean | string;
    showParentTitle?: boolean;
    showParentTitleOrTitle?: boolean;
    showAirTime?: boolean;
    showAirDateTime?: boolean;
    showChannelName?: boolean;
    showTitle?: boolean | string;
    showYear?: boolean | string;
    showDetailsMenu?: boolean;
    missingIndicator?: boolean;
    showLocationTypeIndicator?: boolean;
    showSeriesYear?: boolean;
    showUnplayedIndicator?: boolean;
    showChildCountIndicator?: boolean;
    lines?: number;
    context?: string | null;
    action?: string | null;
    defaultShape?: string;
    indexBy?: string;
    parentId?: string | null;
    showMenu?: boolean;
    cardCssClass?: string | null;
    cardClass?: string | null;
    centerPlayButton?: boolean;
    overlayInfoButton?: boolean;
    autoUpdate?: boolean;
    cardFooterAside?: string;
    includeParentInfoInTitle?: boolean;
    maxLines?: number;
    overlayMarkPlayedButton?: boolean;
    overlayRateButton?: boolean;
    showAirEndTime?: boolean;
    showCurrentProgram?: boolean;
    showCurrentProgramTime?: boolean;
    showItemCounts?: boolean;
    showPersonRoleOrType?: boolean;
    showProgressBar?: boolean;
    showPremiereDate?: boolean;
    showRuntime?: boolean;
    showSeriesTimerTime?: boolean;
    showSeriesTimerChannel?: boolean;
    showSongCount?: boolean;
    width?: number;
    showChannelLogo?: boolean;
    showLogo?: boolean;
    serverId?: string;
    collectionId?: string | null;
    playlistId?: string | null;
    defaultCardImageIcon?: string;
    disableHoverMenu?: boolean;
    disableIndicators?: boolean;
    showGroupCount?: boolean;
    containerClass?: string;
    noItemsMessage?: string;
}
