name: Deploy 🏗️

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
      commit:
        required: false
        type: string
      comment:
        required: false
        type: boolean
      pr_number:
        required: true
        type: number
      workflow_run_id:
        required: true
        type: number
      artifact_name:
        required: false
        type: string
        default: frontend

jobs:
  progress-comment:
    name: Progress Comment
    if: ${{ always() }}
    uses: ./.github/workflows/__job_messages.yml
    secrets:
      JF_BOT_TOKEN: ${{ secrets.JF_BOT_TOKEN }}
    with:
      branch: ${{ inputs.branch }}
      commit: ${{ inputs.commit }}
      pr_number: ${{ inputs.pr_number }}
      comment: true
      in_progress: true

  cf-pages:
    name: CloudFlare Pages 📃
    runs-on: ubuntu-latest
    environment: 
      name: ${{ inputs.branch == 'jellyfin/jellyfin-web/master' && 'Production' || 'Preview' }}
      url: ${{ steps.cf.outputs.deployment-url }}
    outputs:
      url: ${{ steps.cf.outputs.deployment-url }}

    steps:
      - name: Download workflow artifact ⬇️
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: ${{ inputs.artifact_name }}
          path: dist
          run-id: ${{ inputs.workflow_run_id }}
          github-token: ${{ github.token }}

      - name: Publish to Cloudflare Pages 📃
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        id: cf
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=jellyfin-web --branch=${{ inputs.branch }}

  compose-comment:
    name: Compose and push comment 📝
    # Always run so the comment is composed for the workflow summary
    if: ${{ always() }}
    uses: ./.github/workflows/__job_messages.yml
    secrets: inherit
    needs:
      - cf-pages
    with:
      branch: ${{ inputs.branch }}
      commit: ${{ inputs.commit }}
      preview_url: ${{ needs.cf-pages.outputs.url }}
      pr_number: ${{ inputs.pr_number }}
      comment: true
      in_progress: false
